############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Portfolio"
url = "/portfolio"
weight = 3

[[main]]
weight = 4
name = "Carpentry"

[[main]]
weight = 5
name = "Rentals"

[[main]]
name = "Contact Us"
url = "/contact"
weight = 7

[[main]]
parent = "Carpentry"
name = "Fine Furniture"
url = "/furniture"

[[main]]
parent = "Carpentry"
name = "Crating Services"
url = "/crates"

[[main]]
parent = "Carpentry"
name = "Built in Furniture"
url = "/built-in"

[[main]]
parent = "Carpentry"
name = "Furniture Repair"
url = "/repairs"

[[main]]
parent = "Carpentry"
name = "Chicken Coops"
url = "/coops"

[[main]]
parent = "Carpentry"
name = "Custom Dowels"
url = "/dowels"

[[main]]
parent = "Carpentry"
name = "Picture Frames"
url = "/frames"

[[main]]
parent = "Rentals"
name = "Wedding Rentals"
url = "/wedding-rentals"

[[main]]
parent = "Rentals"
name = "Party Rentals"
url = "/party-rentals"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Portfolio"
url = "/portfolio"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
